name: nfungible
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sliver_tools: ^0.2.9
  http: ^0.13.5
  flutter_gen_runner: ^5.2.0
  flutter_svg: ^2.0.1
  sizer: ^2.0.15
  font_awesome_flutter: ^10.4.0
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  graphql_flutter: ^5.1.1
  palette_generator: ^0.3.3+2
  flutter_animate: ^4.1.0
  carousel_slider: ^4.2.1
  dropdown_button2: ^1.9.4
  customizable_counter: ^1.0.4
  permission_handler: ^10.2.0
  file_picker: ^5.2.5
  cached_network_image: ^3.2.3
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
