name: nfungible
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.0.9
  sliver_tools: ^0.2.9
  http: ^0.13.5
  flutter_gen_runner: ^5.2.0
  flutter_svg: ^2.0.1
  sizer: ^2.0.15
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.0.0
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  graphql_flutter: ^5.1.1
  cached_network_image: ^3.2.3
  palette_generator: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
